# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indicesGreaterThan <- function(x, threshold) {
    .Call('_scJLIM_indicesGreaterThan', PACKAGE = 'scJLIM', x, threshold)
}

indicesIsTrue <- function(x) {
    .Call('_scJLIM_indicesIsTrue', PACKAGE = 'scJLIM', x)
}

perm_test <- function(assoc1, permmat, ld0, ld2, R2thr, lambda_t) {
    .Call('_scJLIM_perm_test', PACKAGE = 'scJLIM', assoc1, permmat, ld0, ld2, R2thr, lambda_t)
}

